# Generated by Django 3.2.5 on 2024-10-31 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_busshift_busstop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busshift',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='busshift',
            name='start_time',
        ),
    ]
